import 'package:lyricusic/models/songs.dart';

import '/models/singer.dart';

import '/models/languages.dart';

const List Data = [
  Languages(
    "https://www.nme.com/wp-content/uploads/2018/04/pjimage-33-696x442.jpg",
    "English",
    "L1",
  ),
  Languages(
    "https://i.pinimg.com/564x/2b/db/23/2bdb23129638635d4d5cc2a693e1c12f.jpg",
    "Hindi/Urdu",
    "L2",
  ),
  Languages(
    "https://static.billboard.com/files/media/enrique-iglesias-nov-2016-live-billboard-1548-768x433.jpg",
    "Spanish",
    "L3",
  ),
];

const List Singers = [
  Singer("ZM", "Zayn Malik", "L1",
      "https://mtv.mtvnimages.com/uri/mgid:ao:image:mtv.com:100615?height=729&width=1296&format=jpg&quality=.7"),
  Singer("TS", "Taylor Swift", "L1",
      "https://hips.hearstapps.com/hmg-prod.s3.amazonaws.com/images/gettyimages-455753378-1508516629.jpg?crop=1.00xw:0.376xh;0,0.0421xh&resize=980:*"),
  Singer("ES", "Ed Sheeran", "L1",
      "https://static.billboard.com/files/2021/06/ed-sheeran-2011-billboard-1548-1623680247-compressed.jpg"),
  Singer("DL", "Dua Lipa", "L1",
      "https://i.ytimg.com/vi/wuKpMIhXBb4/maxresdefault.jpg"),
  Singer("AA", "Atif Aslam", "L2",
      "https://thenational-the-national-prod.cdn.arcpublishing.com/resizer/Qhp2EBg432cI-MZY7wWMnT0DYWs=/800x0/filters:format(jpg):quality(70)/cloudfront-eu-central-1.images.arcpublishing.com/thenational/Z2SDN3ASABUG5G6NVQMTOPOCFY.jpg"),
  Singer("AS", "Arjit Singh", "L2",
      "https://images.hindustantimes.com/rf/image_size_630x354/HT/p2/2020/02/18/Pictures/_c111f9ce-5212-11ea-b246-02cea10d1852.jpg"),
  Singer("EI", "Enrique Igleasias", "L3",
      "https://static.billboard.com/files/media/enrique-iglesias-performance-2014-billboard-1548-compressed.jpg"),
  Singer("SA", "Shakira", "L3",
      "https://en.amwalalghad.com/wp-content/uploads/2018/07/Shakira.jpg"),
];

const songs = [
  const Songs(
      name: "Dusk Till Dawn",
      singerid: "ZM",
      isLoveSong: false,
      lyrics: [
        "Not tryna be indie",
        "Not tryna be cool",
        "Just tryna be in this",
        "Tell me, are you too?",
        // "Can you feel where the wind is?",
        // "Can you feel it through",
        // "All of the windows",
        // "Inside this room?",
        // "Cause I wanna touch you baby",
        // "And I wanna feel you too",
        // "I wanna see the sunrise",
        // "On your sins just me and you",
        // "Light it up, on the run",
        // "Let's make love tonight",
        // "Make it up, fall in love, try",
        // "Baby, I am right here",
        // "But you'll never be alone",
        // "I'll be with you from dusk till dawn",
        // "I'll be with you from dusk till dawn",
        // "Baby, I am right here",
        // "I'll hold you when things go wrong",
        // "I'll be with you from dusk till dawn",
        // "I'll be with you from dusk till dawn"
        //     "Baby, I am right here",
        // "I'll be with you from dusk till dawn",
        // "Baby, I am right here",
        // "I'll be with you from dusk till dawn",
        // "Baby, I'm right here",
        // "We were shut like a jacket",
        // "So do your zip",
        // "We would roll down the rapids",
        // "To find a wave that fits",
        // "Can you feel where the wind is?",
        // "Can you feel it through",
        // "All of the windows",
        // "Inside this room?",
        // "Cause I wanna touch you baby",
        // "And I wanna feel you too",
        // "I wanna see the sunrise",
        // "On your sins just me and you",
        // "Light it up, on the run",
        // "Let's make love tonight",
        // "Make it up, fall in love, try",
        // "Baby, I am right here",
        // "But you'll never be alone",
        // "I'll be with you from dusk till dawn",
        // "I'll be with you from dusk till dawn",
        // "Baby, I am right here",
        // "I'll hold you when things go wrong",
        // "I'll be with you from dusk till dawn",
        // "I'll be with you from dusk till dawn",
        // "Baby, I am right here",
        // "I'll be with you from dusk till dawn",
        // "Baby, I am right here",
        // "I'll be with you from dusk till dawn",
        // "Baby, I am right here",
        // "Go, give love to your body",
        // "It's only you that can stop it",
        // "Go, give love to your body",
        // "It's only you that can stop it",
        // "Go, give love to your body",
        // "It's only you that can stop it",
        // "Go, give love to your body",
        // "Go, give love to your body",
        // "But you'll never be alone",
        // "I'll be with you from dusk till dawn",
        // "I'll be with you from dusk till dawn",
        // "Baby, I am right here",
        // "I'll hold you when things go wrong",
        // "I'll be with you from dusk till dawn",
        // "I'll be with you from dusk till dawn",
        // "Baby, I am right here",
        // "I'll be with you from dusk till dawn",
        // "Baby, I am right here",
        // "I'll be with you from dusk till dawn",
        // "Baby, I am right here",
      ],
      isRap: false,
      isRock: true),
  Songs(
      name: "Pillow Talk",
      isRock: false,
      isRap: false,
      isLoveSong: true,
      singerid: "ZM",
      lyrics: [
        "Climb on board",
        "We'll go slow and" 
        "high tempo",
        "Light and dark",
        "Hold me hard and mellow"
      ]),
  Songs(
      lyrics: [
        "We were both young" ,
        "when I first saw you",
        "I close my eyes", 
        "and the flashback starts",
        "I'm standin' there",
        "On a balcony in", 
        "summer air See the lights,",
        "see the party, the ball gowns",
        "See you make your way", 
        "through the crowd",
        "And say, 'Hello'",
        "Little did I know",
      ],
      singerid: "TS",
      isLoveSong: true,
      isRap: false,
      isRock: false,
      name: "Love Story"),
  Songs(
      name: "Blank Space",
      isRock: false,
      isRap: false,
      isLoveSong: true,
      singerid: "TS",
      lyrics: [
        "Nice to meet you",
        ", where you been?",
        "I could show you", 
        "incredible things",
        "Magic, madness, heaven, sin",
        "Saw you there and I thought",
        "Oh, my God, look at that face",
        "You look like my next mistake",
        "Love's a game, wanna play?",
        "\" Ay",
      ]),
  Songs(
      name: "Shape Of You",
      singerid: "ES",
      isRock: true,
      isLoveSong: true,
      isRap: true,
      lyrics: [
        "The club isn't the best",
        "place to find a lover",
        "So the bar is where I go",
        "Me and my friends at the", 
        "table doing shots",
        "Drinking fast and then ",
        "we talk slow",
        "And you come over and start up", 
        "a conversation with just me",
        "And trust me I'll give it a", 
        "chance now Take my hand, stop",
        "put Van the Man on the jukebox",
        "And then we start to dance, and",
        "now I'm singing like",
      ]),
  Songs(
      name: "Photograph",
      singerid: "ES",
      isLoveSong: true,
      isRock: false,
      isRap: false,
      lyrics: [
        "Loving can hurt, ",
        "loving can hurt sometimes",
        "But it's the only thing that I know",
        "When it gets hard,", 
        "you know it can get hard", 
        "sometimes It is the only",
        "thing makes us feel alive",
      ]),
  Songs(
      name: "Levitating",
      lyrics: [
        "If you wanna run away with me," ,
        "I know a galaxy",
        "And I can take you for a ride",
        "I had a premonition", 
        "that we fell into a rhythm",
        "Where the music", 
        "don't stop for life",
        "Glitter in the sky,", 
        "glitter in my eyes",
        "Shining just the way I like",
        "If you're feeling", 
        "like you need a", 
        "little bit of company",
        "You met me at the perfect time",
      ],
      isRap: false,
      isRock: true,
      isLoveSong: false,
      singerid: "DL"),
  Songs(
      name: "New Rules",
      isRap: false,
      singerid: "DL",
      isLoveSong: false,
      isRock: true,
      lyrics: [
        "Talkin' in my sleep at night," ,
        "makin' myself crazy",
        "(Out of my mind, out of my mind)",
        "Wrote it down and", 
        "read it out, hopin' ",
        "it would save me",
        // "(Too many times, too many times)",
      ]),
  Songs(
      name: "What is Love",
      singerid: "O1",
      isRock: false,
      isLoveSong: true,
      isRap: false,
      lyrics: [
        "Oh, I don't know", 
        "why you're not there",
        "I give you my love," 
        "but you don't care",
        "So what is right", 
        "and what is wrong?",
        "Give me a sign",
      ]),
  Songs(
      name: "Tera Hone Laga Hoon",
      lyrics: [
        "Shining in the setting sun", 
        "like a pearl up on the ocean",
        "Come and feel me, o feel me",
        "Shining in the setting", 
        "sun like a pearl up on the ocean",
        "Come and heal me, o heal me",
      ],
      isRap: false,
      isLoveSong: true,
      isRock: false,
      singerid: "AA"),
  Songs(
    name: "Sooraj Dooba Hai",
    singerid: "AS",
    isRock: true,
    isRap: false,
    isLoveSong: true,
    lyrics: [
      "Matlabi ho ja zara matlabi",
      "Duniya ki sunta hai kyun",
      "Khud ki bhi sun le kabhi",
    ],
  ),
  Songs(
      name: "Bailando",
      lyrics: [
        "Bless 'em and", 
        "there ain't no stress",
        "And this one is", 
        "straight for di girldem",
        "Enrique Iglesias", 
        
      ],
      isLoveSong: false,
      isRock: true,
      isRap: true,
      singerid: "EI"),
  Songs(
      name: "Chantanje",
      singerid: "SA",
      isRap: false,
      isRock: true,
      isLoveSong: false,
      lyrics: [
        "Hola, mírame",
        "Ho-hola, mírame",
        "Cuando estás bien,", 
        "te alejas de mí",
        "Te sientes sola,", 
        "y siempre estoy ahí",
        "Es una guerra", 
        "de toma y dame",
        "Pues dame de", 
        "eso que tiene' ahí",
      ])
];
